README: make some requirements better foundable
muesli4/mpd-touch-screen-gui pull request #5
Opened 2020-08-22 07:49 UTC by doronbehar

Add `libconfig` as it's needed and it was missing from README.
Add other usually found but not trivial deps such as pkg-config.
Add link to libwtk-sdl2 as it's not packaged by any GNU/Linux distro
as of today.

See
- https://repology.org/projects/?maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=&search=libwtk-sdl2
- https://repology.org/projects/?maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=&search=icu-uc

2020-08-22 12:15 UTC, muesli4 requested changes
Thanks a lot for contributing.

* I do not think foundable is a word (or the word you're looking for). For example, you could use: _Improve findability of requirements_
* Please start the first verb in the commit message with an upper-case letter.
* Since you already listed your changes so neatly, would you mind using points in the commit message? That improves the visibility by a lot.
* Expand `deps` to `dependencies`.

2020-08-22 12:15 UTC, muesli4 commented on README.md
> +## Native (host machine) Requirements
I do not understand what you mean by `Native Requierements`. Could you rename that subsection just to `Host`?

2020-08-22 12:15 UTC, muesli4 commented on README.md
> +* C++17 compiler such as Gcc
Please use `gcc` (formatted as code).

2020-08-24 08:08 UTC, doronbehar commented on README.md
> +## Native (host machine) Requirements
Build requirements should be even better.

2020-08-24 08:10 UTC, doronbehar commented on README.md
> +* C++17 compiler such as Gcc
:+1:.

2020-08-24 08:12 UTC, doronbehar commented
@muesli4 I'm currently unable to edit the commit message - using GitHub's web interface as my only mean (I'm not at home). So please feel free to squash and edit the commit message of the PR when you merge. I did update the README itself.

2020-08-24 12:43 UTC, muesli4 commented
The slightly modified version has been merged. Thanks!

2020-08-24 12:43 UTC, closed without merging